import os
import time

os.system("clear")
print("[--------------------]")
print("0%  |    Time >> 15s C")
time.sleep(1)
os.system("clear")
print("[--------------------]")
print("0%  |      Time >> 16s")
time.sleep(1)
os.system("clear")
print("[#-------------------]")
print("5%  |      Time >> 15s")
time.sleep(1)
os.system("clear")
print("[#-------------------]")
print("5%  |      Time >> 14s")
time.sleep(1)
os.system("clear")
print("[##------------------]")
print("10%  |      Time >> 13s")
time.sleep(1)
os.system("clear")
print("[####----------------]")
print("20%  |      Time >> 12s")
time.sleep(1)
os.system("clear")
print("[########------------]")
print("20%  |      Time >> 11s")
time.sleep(0.11)
os.system("clear")
print("[########------------]")
print("40%  |      Time >> 10s")
time.sleep(1)
os.system("clear")
print("[##########----------]")
print("40%  |      Time >> 9s")
time.sleep(0.1)
os.system("clear")
print("[##########----------]")
print("50%  |      Time >> 9s")
time.sleep(0.1)
os.system("clear")
print("[##########----------]")
print("50%  |      Time >> 8s")
time.sleep(1)
os.system("clear")
